### ISSUE TITLE
Android Warning - Setting a timer for a long period of time

### ISSUE THREAD

**Issue by superKalo** [matpaul/redux-timer-middleware#4]
Thanks for the library!

I've started a couple of timers for my project, like the one below:

```
dispatch({
  type: START_TIMER,
  payload: {
    actionName: 'TOKEN_EXPIRED',
    timerName: 'refreshToken',
    timerInterval: 45 * 60 * 1000,
  },
});
```

On Android, I'm getting one of these warnings for for every timer. I guess that's normal, right?

```
Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setInterval with duration 2640000ms)
- node_modules/expo/build/environment/muteWarnings.fx.js:17:23 in warn
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:274:8 in setInterval
- node_modules/redux-timer-middleware/lib/index.js:87:73 in <unknown>
- node_modules/redux-timer-middleware/lib/index.js:40:35 in <unknown>
* src/actions/authentication.actions.ts:67:13 in <unknown>
* src/config/application-loading.tsx:129:33 in _callee$
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:30 in invoke
```

Is there any workaround to muting these warnings?

**Comment by matpaul** [comment]
@superKalo Hi, this warning from RN and fix is simple - change your logic and do not make big interval more than 2640000ms (2 700 000 in your example)

**Comment by superKalo** [comment]
> @superKalo Hi, this warning from RN and fix is simple - change your logic and do not make big interval more than 2640000ms (2 700 000 in your example)

Hi @matpaul , thanks for your reply. I don't think that's the issue though. I tried to set a timer with a lot less - 300 000ms (5 min).

```
dispatch({
  type: START_TIMER,
  payload: {
    actionName: 'TOKEN_EXPIRED',
    timerName: 'refreshToken',
    timerInterval: 5 * 60 * 1000, // 300 000ms
  },
});
```

Once again warning appears:

```
Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setInterval with duration 300000ms)
```

**Comment by superKalo** [comment]
I think it's related to https://github.com/facebook/react-native/issues/12981 and as of the time of me writing this - there is no solution.

I've used a workaround to at least hide the annoying warning.

```javascript
import { YellowBox } from 'react-native';

YellowBox.ignoreWarnings(['Setting a timer']);
```

How much of a performance/battery effect would that have I wonder? What do you think?

**Comment by matpaul** [comment]
@superKalo we use twilio chat sdk in our app and see same warning, everything is ok =)

**Comment by superKalo** [comment]
All right, thanks!
